### ISSUE TITLE
Should `validateOrFail` method return array?

### ISSUE THREAD

**Issue by axmad386** [kodepandai/laravel-api-response#2]
https://github.com/kodepandai/laravel-api-response/blob/166847ea9a997d4be735c78417a7fa86c19f8cb2/src/ApiResponse.php#L119-L124

Should `validateOrFail` method return validated input array? This will usefull for sanitizing user input. For now this method return `void`.

**Comment by lakuapik** [comment]
that would be great! PR is welcome

**Comment by lakuapik** [comment]
Added here https://github.com/kodepandai/laravel-api-response/commit/06764a5c63e5e7f2411aa54de172861a8caa2a71, @axmad386 thank you for the feedback!
