### ISSUE TITLE
TODO: Add configuration to allow custom api response structure

### ISSUE THREAD

**Issue by lakuapik** [kodepandai/laravel-api-response#5]
Some user might want to have a custom response structure.

For now, it can be achived by extending the ApiResponse class.

The issue is, the other exception like ApiException and ApiValidationException still uses the original ApiResponse class. So it will not change the response structure for the user.

We need a config file to map which ApiReponse class to be used in application.

**Comment by axmad386** [comment]
@lakuapik can you give example how the config looks like?

**Comment by lakuapik** [comment]
@axmad386 probably just a simple config like


```php

//file: config/api-response.php

return [
    `api_response_class` => \KodePandai\ApiResponse\ApiResponse::class,
];

```

then we bind the api response class to container and use the binding everywhere we need it.

**Comment by axmad386** [comment]
Love this idea @lakuapik. I can add this feature but not this time. Is this feature urgent?

**Comment by lakuapik** [comment]
No, feel free to open PR anytime.

**Comment by lakuapik** [comment]
For this one, we should have a config file to override ApiResponse class.

**Comment by lakuapik** [comment]
@axmad386 i have implemented a facade and interface so user can override ApiResponse class. will be released in v2. please check beta branch.
