### ISSUE TITLE
BUG: exception thrown when request being throttled

### ISSUE THREAD

**Issue by lakuapik** [kodepandai/laravel-api-response#7]
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/20186786/197192698-0e0a5d04-9a8d-47f0-b165-3aec7cae8e4a.png">

**Comment by axmad386** [comment]
Ini contoh kasusnya pas apa ya mas?

**Comment by lakuapik** [comment]
@axmad386 it happened when a route using laravel throttle middleware.

by default, the middleware will add throttle header to the response, and laravel expect the response class is a symfony response class. meanwhile our api response class is just a fluent class, not extending the laravel/symfony response class.

**Comment by axmad386** [comment]
@lakuapik so basically we can solve this by extending ApiResponse class with symphony response?

**Comment by lakuapik** [comment]
@axmad386 yup just like that

**Comment by lakuapik** [comment]
it could be a big refactor tho

**Comment by axmad386** [comment]
@lakuapik I found core of the problems. Actually this issue triggered on Exception Handler part. Laravel didn't recognize Responsable automatically. Don't know why, but this will solve this problem
```php
// in src/ExceptionHandler
    public static function renderAsApiResponse(Throwable $e, Request $request)
    {
        if ($e instanceof ApiException) {
            return $e->render();
        }

        try {
            $self = new self();

            $traces = $self->getTraces($e);

            return ApiResponse::error($traces ? ['_traces' => $traces] : [])
                ->message($self->getMessage($e))
                ->statusCode($self->getStatusCode($e))
                // here we should call toResponse method manually
                ->toResponse($requset);
        } //.
        catch (\Throwable $e) {
            return $e;
        }
    }

```

Then in  `app/Exceptions/Handler.ph` we can use it like this
```php
// file: Exception/Handler.php

use KodePandai\ApiResponse\ExceptionHandler as ApiExceptionHandler;

// new laravel (>= 8)
public function register()
{
    $this->renderable(function (Throwable $e, $request) {
        if ($request->wantsJson() || str_contains($request->path(), 'api')) {
            return ApiExceptionHandler::renderAsApiResponse($e, $request);
        }
    });
}
```

Also, we should mention in documentation when we return `ApiResponse::error()` on laravel exception handler file, we should call `toResponse` method explicitly

For example
```php
        $this->renderable(function (AuthenticationException $e, Request $request) {
            return ApiResponse::error()
                ->message('Unauthorized')
                ->statusCode(401)
                ->toResponse($request); // this part is required

        });

```

**Comment by lakuapik** [comment]
@axmad386 PR are welcome 😁
